name: Horusec Scan

on:
  push:
    branches:
      - main

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Horusec
        id: run_horusec
        uses: fike/horusec-action@main
        with:
          arguments: -c=horusec-config.json -p ./
